services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: news_aggregator_app
    container_name: news_aggregator_app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - .:/var/www
      - ./php.ini:/usr/local/etc/php/php.ini
    ports:
      - "8000:8000"  # Map port 80 in the container to port 8000 on your local machine
    networks:
      - app-network

  db:
    image: mysql:8.0
    container_name: news_aggregator_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: news_aggregator
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
